### ISSUE TITLE
Evento de Oaxaca

### ISSUE THREAD

**Issue by sierisimo** [j4Guanatos/Meetup#5]
Fer nos habia invitado a Oaxaca como Comunidad, hay que darle seguimiento.

**Comment by sierisimo** [comment]
@fercho1908 algun comentario en esto?

**Comment by fercho1908** [comment]
Que onda, que bueno que lo mencionas, ya hable con el contacto y me comento que siempre no se va hacer el evento :( asi que podemos dar por cerrado este issue
